### ISSUE TITLE
Category / implement category feature (CRUD)

### ISSUE THREAD

**Issue by earlyoonj** [earlyoonj/expense-schedular#7]
# Todos
- [ ] **[store]** make categorySlice _(createCategory, updateCategory, deleteCategory)_
- [ ] **[status]** create budget setting UI & category edit UI
- [ ] **[transactions form]** create category input component - select, create, edit

# Working Log
